import { Navigate, type RouteObject } from "react-router-dom";
import {
  OwnerStatsPage,
  OwnerGymsListPage,
  OwnerGymCreatePage,
  OwnerGymEditPage,
  OwnerGuestsListPage,
  OwnerGuestDetailPage,
  OwnerEmployeesListPage,
  OwnerEmployeeCreatePage,
  OwnerEmployeeEditPage,
  OwnerPassTypesListPage,
  OwnerPassTypeCreatePage,
  OwnerPassTypeEditPage,
  OwnerPassesListPage,
  OwnerPassDetailPage,
  OwnerLockersListPage,
  OwnerLockerCreatePage,
  OwnerLockerDetailPage,
  OwnerHistoryListPage,
  OwnerHistoryDetailPage,
  OwnerSchedulePage,
  OwnerWorkSchedulePage,
  OwnerSalesReportPage,
  OwnerNotificationsPage,
  OwnerAnalyticsPage,
  OwnerRanksListPage,
  OwnerRankCreatePage,
  OwnerRankEditPage,
  OwnerProductsPage,
  OwnerClassRatingsPage,
} from "../pages/owner/ownerRouteElements";

export const ownerRouteObjects: RouteObject[] = [
  { index: true, element: <Navigate to="dashboard" replace /> },
  { path: "dashboard", Component: OwnerStatsPage },
  { path: "gyms", Component: OwnerGymsListPage },
  { path: "gyms/new", Component: OwnerGymCreatePage },
  { path: "gyms/:gymId", Component: OwnerGymEditPage },
  { path: "guests", Component: OwnerGuestsListPage },
  { path: "guests/:guestId", Component: OwnerGuestDetailPage },
  { path: "employees", Component: OwnerEmployeesListPage },
  { path: "employees/new", Component: OwnerEmployeeCreatePage },
  { path: "employees/:employeeId", Component: OwnerEmployeeEditPage },
  { path: "ranks", Component: OwnerRanksListPage },
  { path: "ranks/new", Component: OwnerRankCreatePage },
  { path: "ranks/:rankId", Component: OwnerRankEditPage },
  { path: "pass-types", Component: OwnerPassTypesListPage },
  { path: "pass-types/new", Component: OwnerPassTypeCreatePage },
  { path: "pass-types/:passTypeId", Component: OwnerPassTypeEditPage },
  { path: "passes", Component: OwnerPassesListPage },
  { path: "passes/:passId", Component: OwnerPassDetailPage },
  { path: "products", Component: OwnerProductsPage },
  { path: "lockers", Component: OwnerLockersListPage },
  { path: "lockers/new", Component: OwnerLockerCreatePage },
  { path: "lockers/:lockerId", Component: OwnerLockerDetailPage },
  { path: "history", Component: OwnerHistoryListPage },
  { path: "history/:logId", Component: OwnerHistoryDetailPage },
  { path: "schedule", Component: OwnerSchedulePage },
  { path: "work-schedule", Component: OwnerWorkSchedulePage },
  { path: "sales-report", Component: OwnerSalesReportPage },
  { path: "analytics", Component: OwnerAnalyticsPage },
  { path: "class-ratings", Component: OwnerClassRatingsPage },
  { path: "notifications", Component: OwnerNotificationsPage },
];
